server:
  # 应用端口。由 .env 文件中的 DOCKER_SERVER_PORT 决定
  port: ${DOCKER_SERVER_PORT}

spring:
  datasource:
    # H2 数据库文件路径。在 Docker 中，此路径会指向一个挂载的数据卷
    url: jdbc:h2:file:./data/kn_ai_chat_db
    driverClassName: org.h2.Driver
    # 数据库用户名和密码，由 .env 文件决定
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  data:
    redis:
      # Redis 配置，全部由 .env 文件决定
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
      timeout: 1800000
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 5
          min-idle: 0


tools:
  google:
    api-key: ${GOOGLE_API_KEY}
    cx-id: ${GOOGLE_CX_ID}
  brave:
    api-key: ${BRAVE_API_KEY}
  email:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    imap:
      host: ${EMAIL_IMAP_HOST}
      port: ${EMAIL_IMAP_PORT}
  notion:
    api:
      key: ${NOTION_API_KEY}
      version: ${NOTION_API_VERSION}
      base-url: ${NOTION_BASE_URL}
    database:
      id: ${NOTION_DATABASE_ID}

# 微信客服配置，由 .env 文件决定
wechat:
  token: ${WECHAT_TOKEN}
  encoding-aes-key: ${WECHAT_AES_KEY}
  corp-id: ${WECHAT_CORP_ID}
  secret: ${WECHAT_SECRET}

# 管理后台密码，由 .env 文件决定
admin:
  password: ${ADMIN_PASSWORD}

# --- AI 服务商的默认配置 (全部从 .env 文件读取) ---
default:
  ai:
    base-url: ${DEFAULT_AI_BASE_URL}
    api-key: ${AI_API_KEY}
    model: ${DEFAULT_AI_MODEL}
    system-prompt: ${DEFAULT_AI_SYSTEM_PROMPT}
    siliconflow:
      base-url: ${SILICONFLOW_BASE_URL}
      image-model: ${SILICONFLOW_IMAGE_MODEL}
      tts-model: ${SILICONFLOW_TTS_MODEL}
      stt-model: ${SILICONFLOW_STT_MODEL}
      voice: ${SILICONFLOW_VOICE}
      vlm-model: ${SILICONFLOW_VLM_MODEL}
    rag:
      enabled: ${RAG_ENABLED}
      rag-model: ${RAG_MODEL}
      rag-base-url: ${RAG_BASE_URL}
      rag-api-key: ${RAG_API_KEY}
  mcp:
    base-url: ${MCP_BASE_URL}
    model: ${MCP_MODEL}
    api-key: ${MCP_API_KEY}

# Flyway 配置
flyway:
  enabled: true
  locations: classpath:db/migration