server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:file:./data/kn_ai_chat_db
    driverClassName: org.h2.Driver
    username: xlike
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 1800000
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 5
          min-idle: 0

wechat:
  token: Gqupbfy3LSKkMCXwg5lm4IYoxvrJCr
  encoding-aes-key: uZgTn9eXmE695qvFE5E6crSKilVvUD34ZUxGm7sfYXx
  corp-id: ww712d8540fe5c9ae1
  secret: R8fNwKftR3T29FGthGacDdvL5G8ldmtDgei_mPN2ZnM
  open-kfid: kfc748b546cc5895d1e
admin:
  password: "xlike"
default:
  ai:
    base-url: https://api.siliconflow.cn/v1/chat/completions
    api-key: sk-lsqccdgbruyeuzjyypnjghyytkccmdgvafrlruaoxqdgrqum
    model: deepseek-ai/DeepSeek-V3
    system-prompt: 你是一个乐于助人的AI助手
    siliconflow:
      base-url: https://api.siliconflow.cn/v1
      image-model: "Kwai-Kolors/Kolors"
      tts-model: "FunAudioLLM/CosyVoice2-0.5B"
      stt-model: "FunAudioLLM/SenseVoiceSmall"
      voice: "speech:cxk:clykbri4i000210pbgcrapso0:whmpulffgeakvrxayxgk"
      vlm-model: "Qwen/Qwen2-VL-72B-Instruct"