services:
  app:
    image: xlike0616/kn_ai_chat:latest
    container_name: kn-ai-chat-app
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - kn-ai-network

  redis:
    image: redis:latest
    container_name: ${REDIS_HOST}
    restart: always
    command: redis-server --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - kn-ai-network

networks:
  kn-ai-network:
    driver: bridge

volumes:
  redis_data: