services:
  app:
    image: xlike0616/kn_ai_chat:1.0.1
    container_name: kn-ai-chat-app
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - WECHAT_TOKEN=${WECHAT_TOKEN}
      - WECHAT_AES_KEY=${WECHAT_AES_KEY}
      - WECHAT_CORP_ID=${WECHAT_CORP_ID}
      - WECHAT_SECRET=${WECHAT_SECRET}
      - WECHAT_OPEN_KFID=${WECHAT_OPEN_KFID}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - AI_API_KEY=${AI_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DATABASE=${REDIS_DATABASE}
      - DOCKER_SERVER_PORT=${DOCKER_SERVER_PORT}
    depends_on:
      - redis
    networks:
      - kn-ai-network

  redis:
    image: redis:latest
    container_name: ${REDIS_HOST}
    restart: always
    command: redis-server --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - kn-ai-network

networks:
  kn-ai-network:
    driver: bridge

volumes:
  redis_data: